### ISSUE TITLE
关于载入存档时会弹出ERROR的报告

### ISSUE THREAD

**Issue by Surgeol** [ProjectSky/MoreBuild#1]
游戏为最新正式版本，且验证过游戏完整性
仅启用了MoreBuild模组，在进入存档的时候会弹出一个ERROR(不论是新开存档还是载入旧档)
目前并未发现其他的触发方法
禁用所有模组，使用纯原版进入档则没有ERROR提示

以下为录频
https://user-images.githubusercontent.com/35412032/153756731-6affbeb8-abeb-4786-a52a-415ff9abe458.mp4
以下为日志(仅包含录频期间产生的log)
[13-02-22_22-00-45_DebugLog.txt](https://github.com/ProjectSky/MoreBuild/files/8055682/13-02-22_22-00-45_DebugLog.txt)

我并不清除是否系个人电脑原因引起的问题，如果真是如此，我对此感到十分抱歉👀

**Comment by ProjectSky** [comment]
已知问题，由于modid变更，导致已废弃的debug模块报错，下个版本修复
https://github.com/ProjectSky/MoreBuild/blob/13a5fce696120609d709cfb498e3cb9ce6c4aba6/media/lua/client/MoreBuildings/ISUILuaWindow.lua#L23
